(() => {
  'use strict';
  const M=window.HakunaMataV2;
  if(!M) throw new Error('Mata core yüklenmedi');
  const {SUBJECTS,EMOJI,uid,esc,fold,todayISO,fmtDate,minute,time,duration,parseDuration,parseMetric,currentState,addMessage,friendly,actionLabel,conflict,writeState,parseRequest,examRows,openDB}=M;
  let mataActive=false, proposal=null, prepared=null, pending=null, pendingOwner=null, injecting=false, busy=false;
  async function guarded(fn){if(busy)return;busy=true;try{await fn();}catch(e){proposal=null;prepared=null;pending=null;window.alert(e.message||'İşlem kaydedilemedi. Yeniden dene.');await renderMata();}finally{busy=false;}}
  function prepare(state){prepared=proposal?.length?M.actionsV4.prepare(state,proposal):null;}
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function messagesHTML(state){return state.assistantMessages.map(m=>`<div class="mata-message ${m.role==='user'?'user':'mata'}">${m.role==='mata'?'<img src="./assets/mata.svg" alt="" class="mata-avatar">':''}<div><div class="mata-bubble">${esc(m.text)}</div><div class="mata-time">${new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit'}).format(new Date(m.time))}</div></div></div>`).join('');}
  function proposalHTML(){if(!prepared)return '';return `<section class="mata-proposal"><strong>Değişiklik önizlemesi</strong><p>Bağlı borçlar dahil aşağıdaki değişiklikler yalnızca onayınla kaydedilir.</p>${prepared.rows.map(row=>`<div class="mata-proposal-row"><div style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(row)}</div></div>`).join('')}<div class="mata-proposal-actions"><button class="secondary-btn" data-mata-cancel>Vazgeç</button><button class="primary-btn" data-mata-apply>Onayla ve kaydet</button></div></section>`;}

  async function renderMata(){if(!mataActive)return;const state=await currentState(),view=$('#view'),actions=$('#topbarActions');if(!view||!actions)return;$('#pageEyebrow').textContent='Hakuna’yı konuşarak yönet';$('#pageTitle').textContent='Mata';actions.innerHTML='<span class="mata-online">● Cihaz içinde</span>';view.innerHTML=`<div class="mata-layout"><section class="card mata-chat-card"><div class="mata-chat-head"><div><div class="card-title">✨ Mata — Hakuna Asistan</div><div class="card-subtitle">Program, görev, borç, deneme ve sorularını normal konuşma diliyle yönet.</div></div><div class="mata-mini"><img src="./assets/mata.svg" alt="Mata"></div></div><div class="mata-messages" id="mataMessages">${messagesHTML(state)}${proposalHTML(state)}</div><div class="mata-input-wrap"><textarea id="mataInput" rows="2" maxlength="1200" placeholder="Mata’ya ne yapmak istediğini yaz…"></textarea><button class="mata-send" data-mata-send aria-label="Gönder">➤</button></div><div class="mata-input-hint">Örn. “11.45’teki türevin başlangıcını 11.35 yap”, “Bugünkü fiziği tamamlandı yap”, “Görev havuzuna 5 test türev ekle”.</div></section><aside class="mata-side">${M.actionEditorV4.html()}<section class="card mata-intro"><div class="mata-character"><img src="./assets/mata.svg" alt="Mata maskotu"></div><div class="mata-intro-copy"><div class="mata-name">Mata 💙</div><p><strong>Mata ne yapar?</strong> Hakuna’da senin elle yapabildiğin temel veri işlemlerini konuşarak yapar: blok ekler, siler, saatini/süresini/tarihini/adını değiştirir, durumunu işaretler; görev ve borç yönetir; deneme ve soru kaydeder.</p><p><strong>Nasıl kullanılır?</strong> Komut ezberleme. “Şunu 10 dakika erkene al”, “bu bloğun başlangıcını 11.35 yap”, “dünkü denemeyi kaydet” gibi doğal yaz. Değişiklikleri önce gösterir, sen onaylayınca uygular.</p></div></section><section class="card mata-examples"><div class="card-title">Deneyebileceğin şeyler</div><div class="card-subtitle">Dokunup düzenleyebilirsin.</div><div class="mata-example-list"><button data-mata-example="11.45'teki türevin başlangıç saatini 11.35 yap">11.45’teki türevin başlangıcını 11.35 yap</button><button data-mata-example="Bugünkü fiziği tamamlandı yap">Bugünkü fiziği tamamlandı yap</button><button data-mata-example="Görev havuzuna 5 test Apotemi Türev ekle">Görev havuzuna 5 test türev ekle</button><button data-mata-example="Orijinal matematik Test 7 Soru 4'ü sorulara ekle">Sorulara kaynak + soru ekle</button><button data-mata-example="Yarın 9-10 paragraf, 10-11 problem, 11.30-12.30 türev koy">Yarının birkaç bloğunu tek mesajda yaz</button></div></section></aside></div>`;
    requestAnimationFrame(()=>{const box=$('#mataMessages');if(box)box.scrollTop=box.scrollHeight;});const input=$('#mataInput');$('[data-mata-send]')?.addEventListener('click',()=>{if(busy)return;const v=input.value;input.value='';handleSend(v)});input?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();const v=input.value;input.value='';handleSend(v);}});$$('[data-mata-example]').forEach(b=>b.onclick=()=>{input.value=b.dataset.mataExample;input.focus();});$('[data-mata-apply]')?.addEventListener('click',applyProposal);$('[data-mata-cancel]')?.addEventListener('click',()=>guarded(async()=>{proposal=null;prepared=null;pending=null;M.conversationV4.reset();const s=await currentState();addMessage(s,'mata','Tamam 💙 Bu işlemleri uygulamadım.');await writeState(s);await renderMata();}));M.actionEditorV4.bind(view,state,actions=>guarded(async()=>{const fresh=await currentState();proposal=actions;pending=null;M.conversationV4.reset();prepare(fresh);addMessage(fresh,'mata','Seçtiğin kayıtlar için önizleme hazır. Henüz değişiklik yapılmadı.');await writeState(fresh);await renderMata();}));markActiveNav();}

  async function handlePending(state,raw){if(!pending)return false;const base=pending.existingActions||[];
    if(pending.type==='duration'){const d=parseDuration(raw);if(!d){addMessage(state,'mata','Süreyi “50 dakika” veya “1 saat” gibi yazabilir misin?');return true;}if(minute(pending.start)+d>1439)throw new Error('Çalışma geceyi aşıyor. İki ayrı blok oluştur.');proposal=[...base,{type:'add_block',date:pending.date,start:pending.start,end:time(minute(pending.start)+d),subject:pending.subject,title:pending.title,metricValue:pending.metric?.value||null,metricUnit:pending.metric?.unit||'test',note:''}];pending=null;addMessage(state,'mata',`${friendly('proposal')} Önizlemeyi hazırladım.`);return true;}
    if(pending.type==='partial_remaining'){const r=parseMetric(raw);if(!r){addMessage(state,'mata','Kalanı “3 test” veya “20 dakika” gibi yazabilir misin?');return true;}proposal=[...base,{type:'status_block',oldBlock:pending.block,status:'partial',remaining:r}];pending=null;addMessage(state,'mata',`${friendly('proposal')} Kalan miktarı da ekledim.`);return true;}
    if(pending.type==='question_fields'){const refParts=[];for(const re of [/(?:test)\s*\d+/ig,/(?:sayfa|sf)\s*\d+/ig,/(?:soru)\s*\d+/ig]){const m=String(raw).match(re);if(m)refParts.push(...m);}let source=String(raw).split(/test\s*\d+|sayfa\s*\d+|sf\s*\d+|soru\s*\d+/i)[0].replace(/[,:-]+$/,'').trim();const reference=refParts.join(' / ')||pending.reference;if(!source||!reference){addMessage(state,'mata','Kaynak ve soru bilgisini birlikte yazar mısın? Örn. “Orijinal, Test 7 / Soru 4”.');return true;}proposal=[...base,{type:'add_question',subject:pending.subject,topic:pending.topic,source,reference,note:''}];pending=null;addMessage(state,'mata',`${friendly('proposal')} Soruyu hazırladım.`);return true;}
    if(pending.type==='exam_rows'){const rows=examRows(raw,pending.examType);if(!rows.length){addMessage(state,'mata','Ders sonuçlarını “Türkçe 35D 5Y, Matematik 32D 6Y 2B” gibi yazar mısın?');return true;}proposal=[...base,{type:'add_exam',examType:pending.examType,date:pending.date,name:pending.name,duration:pending.duration,ranking:'',rows}];pending=null;addMessage(state,'mata',`${friendly('proposal')} Deneme kaydını hazırladım.`);return true;}
    return false;
  }

  function handleSend(text){return guarded(()=>handleSendUnsafe(text));}
  async function handleSendUnsafe(text){const raw=String(text||'').trim();if(!raw)return;const state=await currentState();if(/^(iptal|vazgeç|vazgec|boşver|bosver|hayır|hayir)$/i.test(raw)){pending=null;M.conversationV4.reset();}if(pending&&pendingOwner!==M.actionsV4.owner()){pending=null;throw new Error('Hesap değişti. İsteğini yeniden gönder.');}addMessage(state,'user',raw);proposal=null;prepared=null;if(await handlePending(state,raw)){prepare(state);await writeState(state);return renderMata();}const r=parseRequest(state,raw);if(r.reply){addMessage(state,'mata',r.reply);await writeState(state);return renderMata();}if(r.pending){pending=r.pending;pendingOwner=M.actionsV4.owner();addMessage(state,'mata',`${friendly('clarify')} ${r.message}`);await writeState(state);return renderMata();}if(!r.actions?.length){addMessage(state,'mata',r.message||'Bunu tam anlayamadım.');await writeState(state);return renderMata();}proposal=r.actions;prepare(state);const hasConflict=proposal.some(a=>conflict(state,a));addMessage(state,'mata',`${friendly('proposal')} ${proposal.length===1?'1 işlemi':proposal.length+' işlemi'} hazırladım${hasConflict?' — saat çakışması görüyorum, önizlemeyi kontrol et':''}.`);await writeState(state);await renderMata();}

  function applyProposal(){return guarded(async()=>{if(!prepared)return;const token=prepared;prepared=null;proposal=null;await M.actionsV4.commit(token);await renderMata();});}

  function markActiveNav(){$$('[data-mata-nav]').forEach(b=>b.classList.add('active'));$$('[data-nav]').forEach(b=>b.classList.remove('active'));}
  function addNav(){if(injecting)return;injecting=true;const side=$('#sidebarNav');if(side&&!side.querySelector('[data-mata-nav]')){const b=document.createElement('button');b.className='nav-button';b.dataset.mataNav='1';b.innerHTML='<span class="nav-icon">✨</span><span class="nav-label">Mata</span>';b.onclick=()=>{mataActive=true;renderMata()};const settings=side.querySelector('[data-nav="settings"]');side.insertBefore(b,settings||null);}const bottom=$('#bottomNav');if(bottom&&!bottom.querySelector('[data-mata-nav]')){const b=document.createElement('button');b.dataset.mataNav='1';b.innerHTML='<span class="nav-icon">✨</span><span>Mata</span>';b.onclick=()=>{mataActive=true;renderMata()};const more=bottom.querySelector('[data-nav="more"]');bottom.insertBefore(b,more||null);bottom.classList.add('mata-bottom-nav');}if(mataActive)markActiveNav();injecting=false;}
  function interceptAppNav(){document.addEventListener('click',e=>{const b=e.target.closest?.('[data-nav]');if(!b||!mataActive)return;const target=b.dataset.nav;if(target==='more'){mataActive=false;return;}e.preventDefault();e.stopImmediatePropagation();sessionStorage.setItem('hakuna_mata_target',target);location.reload();},true);}
  function resumeTarget(){const target=sessionStorage.getItem('hakuna_mata_target');if(!target)return;sessionStorage.removeItem('hakuna_mata_target');setTimeout(()=>document.querySelector(`[data-nav="${target}"]`)?.click(),220);}
  function observe(){const ob=new MutationObserver(()=>{addNav();});ob.observe(document.body,{childList:true,subtree:true});}
  async function init(){try{await openDB();}catch(e){console.warn('Mata DB',e);return;}addNav();interceptAppNav();observe();resumeTarget();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
