(() => {
  'use strict';
  const M=window.HakunaMataV2;
  if(!M) throw new Error('Mata core yüklenmedi');
  const {SUBJECTS,fold,todayISO,parseDate,minute,time,duration,fmtDate,parseDuration,parseMetric,detectSubject,detectSubjects,cleanTitle,extractTimes,parseIntervals,findBlock,findByTitle,targetText,chooseBlock,ambiguity}=M;
  function parseBlockCommand(state,text,inheritedDate=todayISO()){
    const n=fold(text),date=parseDate(text,inheritedDate),sub=detectSubject(text),subs=detectSubjects(text),times=extractTimes(text),intervals=parseIntervals(text).intervals;
    if(/\b(programi|programını|programini|gunu|günü)\b.*\b(temizle|bosalt|boşalt|sil)\b/.test(n)){const list=(state.blocks||[]).filter(b=>b.date===date);return list.length?{actions:list.map(oldBlock=>({type:'delete_block',oldBlock}))}:{message:`${fmtDate(date)} zaten boş.`};}
    if(/\bsonrasini\s+(bosalt|temizle|sil)\b|\bsonrasini\b.*\b(bosalt|temizle|sil)\b/.test(n)){const cut=times[0];if(!cut)return {message:'Hangi saatten sonrasını boşaltayım?'};const list=(state.blocks||[]).filter(b=>b.date===date&&minute(b.start)>=minute(cut));return list.length?{actions:list.map(oldBlock=>({type:'delete_block',oldBlock}))}:{message:`${cut} sonrasında blok yok.`};}
    if(/\b(tamamlandi|tamamlandı|bitti|bitirdim|yapildi|yapıldı)\b/.test(n)&&!/\b(gorev|görev|soru|deneme|borc|borç)\b/.test(n)){const t=chooseBlock(state,text,date);if(!t.one)return {message:ambiguity('Bloğu',t.list)};return {actions:[{type:'status_block',oldBlock:t.one,status:'complete'}]};}
    if(/\b(kismen|kısmen)\b/.test(n)){const t=chooseBlock(state,text,date);if(!t.one)return {message:ambiguity('Bloğu',t.list)};const remaining=parseMetric(text);if(!remaining)return {pending:{type:'partial_remaining',block:t.one},message:`${t.one.title} için ne kadar kaldı? “3 test” veya “20 dakika” gibi yazabilirsin.`};return {actions:[{type:'status_block',oldBlock:t.one,status:'partial',remaining}]};}
    if(/\b(tamamlanmadi|tamamlanmadı|yapilmadi|yapılmadı|yapamadim|yapamadım)\b/.test(n)){const t=chooseBlock(state,text,date);if(!t.one)return {message:ambiguity('Bloğu',t.list)};return {actions:[{type:'status_block',oldBlock:t.one,status:'incomplete'}]};}
    if(/\b(sil|kaldir|kaldır|cikar|çıkar|iptal et)\b/.test(n)){const t=chooseBlock(state,text,date);if(!t.one)return {message:ambiguity('Bloğu',t.list)};return {actions:[{type:'delete_block',oldBlock:t.one}]};}

    const editCue=/\b(baslangic|başlangıç|baslama|başlama|bitis|bitiş|suresi|süresi|saatini|adini|adını|notunu|miktarini|miktarını|tarihini|dersini)\b/.test(n);
    if(editCue){const t=chooseBlock(state,text,date);if(!t.one)return {message:ambiguity('Düzenlenecek bloğu',t.list)};const b=t.one,patch={};
      if(/\b(baslangic|başlangıç|baslama|başlama)\b/.test(n)){if(times.length<2)return {message:'Yeni başlangıç saatini de yazar mısın?'};patch.start=times[times.length-1];}
      if(/\bsaatini\b/.test(n)&&!/\b(baslangic|başlangıç|baslama|başlama|bitis|bitiş)\b/.test(n)){if(times.length<2)return {message:'Yeni saati de yazar mısın?'};const ns=times[times.length-1],d=duration(b.start,b.end);patch.start=ns;patch.end=time(minute(ns)+d);}
      if(/\b(bitis|bitiş)\b/.test(n)){if(times.length<2)return {message:'Yeni bitiş saatini de yazar mısın?'};patch.end=times[times.length-1];}
      if(/\b(suresi|süresi)\b/.test(n)){const d=parseDuration(text);if(!d)return {message:'Yeni süreyi “50 dakika” veya “1 saat” gibi yazar mısın?'};patch.end=time(minute(b.start)+d);}
      if(/\b(tarihini)\b/.test(n)){patch.date=parseDate(text,b.date);}
      if(/\b(miktarini|miktarını)\b/.test(n)){const met=parseMetric(text);if(!met)return {message:'Yeni miktarı “5 test” gibi yazar mısın?'};patch.metricValue=met.value;patch.metricUnit=met.unit;}
      if(/\b(dersini)\b/.test(n)&&subs.length){const s=subs[subs.length-1];patch.subject=s.subject;}
      const nameMatch=String(text).match(/(?:adını|adini)\s+(.+?)\s+(?:yap|olarak değiştir|olarak degistir)/i);if(nameMatch)patch.title=nameMatch[1].trim();
      const noteMatch=String(text).match(/notunu\s+(.+?)\s+(?:yap|yaz|olarak değiştir|olarak degistir)/i);if(noteMatch)patch.note=noteMatch[1].trim();
      if(!Object.keys(patch).length)return {message:'Hangi özelliğini değiştireceğimi anlayamadım.'};
      if(patch.start&&minute(patch.start)>=minute(patch.end||b.end))return {message:'Yeni başlangıç saati bitişten önce olmalı.'};if(patch.end&&minute(patch.end)<=minute(patch.start||b.start))return {message:'Yeni bitiş saati başlangıçtan sonra olmalı.'};
      return {actions:[{type:'edit_block',oldBlock:b,patch}]};
    }

    if(/\b(tasi|taşı|kaydir|kaydır|öne al|geriye al|erkene al|ileri al|ertelee?|aktar)\b/.test(n)){const t=chooseBlock(state,text,date);if(!t.one)return {message:ambiguity('Taşınacak bloğu',t.list)};const b=t.one;let newStart=times.length>=2?times[times.length-1]:null;let newDate=parseDate(text,b.date);const rel=parseDuration(text);if(!newStart&&rel){const sign=/erkene|öne al/.test(n)?-1:/ileri al|geriye al|erte/.test(n)?1:0;if(sign)newStart=time(minute(b.start)+sign*rel);}if(!newStart&&newDate===b.date)return {message:'Hangi saate veya güne taşıyayım?'};newStart=newStart||b.start;const d=duration(b.start,b.end);return {actions:[{type:'edit_block',oldBlock:b,patch:{date:newDate,start:newStart,end:time(minute(newStart)+d)}}]};}

    if(/\b(degistir|değiştir|yerine)\b/.test(n)&&subs.length>=2){const oldS=subs[0],newS=subs[subs.length-1],t=findBlock(state,{date,subject:oldS.subject,start:times[0]||null,title:oldS.title});if(!t.one)return {message:ambiguity('Değiştirilecek bloğu',t.list)};return {actions:[{type:'edit_block',oldBlock:t.one,patch:{subject:newS.subject,title:newS.title}}]};}

    if(intervals.length){const actions=[];const normalized=parseIntervals(text).normalized;for(let i=0;i<intervals.length;i++){const iv=intervals[i],seg=normalized.slice(iv.endIndex,intervals[i+1]?.index??normalized.length);const s=detectSubject(seg)||detectSubject(normalized.slice(Math.max(0,iv.index-35),Math.min(normalized.length,iv.endIndex+70)))||sub;if(!s)continue;const metric=parseMetric(seg)||parseMetric(text);const title=cleanTitle(seg,s.title);actions.push({type:'add_block',date,start:iv.start,end:iv.end,subject:s.subject,title:title.length>2?title:s.title,metricValue:metric?.value||null,metricUnit:metric?.unit||'test',note:''});}if(actions.length)return {actions};}
    if(sub&&times.length){const start=times[0],dur=parseDuration(text);if(!dur)return {pending:{type:'duration',date,start,subject:sub.subject,title:cleanTitle(text,sub.title),metric:parseMetric(text)},message:`${sub.title} ${start}'da başlasın. Ne kadar sürsün?`};return {actions:[{type:'add_block',date,start,end:time(minute(start)+dur),subject:sub.subject,title:cleanTitle(text,sub.title),metricValue:parseMetric(text)?.value||null,metricUnit:parseMetric(text)?.unit||'test',note:''}]};}
    return null;
  }

  function parseTaskCommand(state,text){const n=fold(text);if(!/\b(gorev|görev|havuz)\b/.test(n))return null;const sub=detectSubject(text)||{subject:'Diğer',title:'Görev'},metric=parseMetric(text),ints=parseIntervals(text).intervals,date=parseDate(text,todayISO());
    const list=(state.tasks||[]),target=findByTitle(list,targetText(text));
    if(/\b(programa|takvime|plana)\b.*\b(koy|ekle|yerlestir|yerleştir)\b/.test(n)){if(!target.one)return {message:ambiguity('Görevi',target.list)};if(!ints.length)return {message:'Görevi hangi saat aralığına koyayım? Örn. 14.00–15.00.'};const iv=ints[0];return {actions:[{type:'schedule_task',item:target.one,date,start:iv.start,end:iv.end}]};}
    if(/\b(sil|kaldir|kaldır|cikar|çıkar)\b/.test(n)){if(!target.one)return {message:ambiguity('Görevi',target.list)};return {actions:[{type:'delete_task',item:target.one}]};}
    if(/\b(tamamlandi|tamamlandı|bitti|bitirdim)\b/.test(n)){if(!target.one)return {message:ambiguity('Görevi',target.list)};return {actions:[{type:'toggle_task',item:target.one,completed:true}]};}
    if(/\b(geri ac|geri aç|aktif yap|tamamlanmadi|tamamlanmadı)\b/.test(n)){if(!target.one)return {message:ambiguity('Görevi',target.list)};return {actions:[{type:'toggle_task',item:target.one,completed:false}]};}
    if(/\b(ekle|olustur|oluştur|yaz)\b/.test(n)){const title=cleanTitle(text,sub.title).replace(/gorev havuzuna|görev havuzuna/ig,'').trim()||sub.title;return {actions:[{type:'add_task',title,subject:sub.subject,value:metric?.value||null,unit:metric?.unit||'test',note:''}]};}
    return null;
  }

  function parseDebtCommand(state,text){const n=fold(text);if(!/\b(borc|borç)\b/.test(n))return null;const list=state.debts||[],target=findByTitle(list,targetText(text)),metric=parseMetric(text),sub=detectSubject(text)||{subject:'Diğer',title:'Borç'},ints=parseIntervals(text).intervals,date=parseDate(text,todayISO());
    if(/\b(programa|takvime|plana)\b.*\b(koy|ekle|yerlestir|yerleştir)\b/.test(n)){if(!target.one)return {message:ambiguity('Borcu',target.list)};if(!ints.length)return {message:'Borcu hangi saat aralığına koyayım?'};const iv=ints[0];return {actions:[{type:'schedule_debt',item:target.one,date,start:iv.start,end:iv.end}]};}
    if(/\b(sil|kaldir|kaldır|cikar|çıkar)\b/.test(n)){if(!target.one)return {message:ambiguity('Borcu',target.list)};return {actions:[{type:'delete_debt',item:target.one}]};}
    if(/\b(ekle|olustur|oluştur|yaz)\b/.test(n)){if(!metric)return {message:'Borç miktarını da yazar mısın? Örn. “3 test” veya “40 dakika”.'};const title=cleanTitle(text,sub.title).replace(/borca|borçlara|borc|borç/ig,'').trim()||sub.title;return {actions:[{type:'add_debt',title,subject:sub.subject,value:metric.value,unit:metric.unit,sourceDate:date}]};}
    return null;
  }

  function parseQuestionCommand(state,text){const n=fold(text);if(!/(sorulara|soru havuz|cozdur|çözdür|cozdurulecek|çözdürülecek|soru kaydet|soruyu sil|soruyu kaldir|soruyu kaldır|soru cozuldu|soru çözüldü)/.test(n))return null;const target=findByTitle(state.questions||[],targetText(text));
    if(/\b(sil|kaldir|kaldır|cikar|çıkar)\b/.test(n)){if(!target.one)return {message:ambiguity('Soruyu',target.list)};return {actions:[{type:'delete_question',item:target.one}]};}
    if(/\b(cozuldu|çözüldü|cozdum|çözdüm|kapat)\b/.test(n)){if(!target.one)return {message:ambiguity('Soruyu',target.list)};return {actions:[{type:'toggle_question',item:target.one,status:'solved'}]};}
    if(/\b(geri ac|geri aç|acik yap|açık yap)\b/.test(n)){if(!target.one)return {message:ambiguity('Soruyu',target.list)};return {actions:[{type:'toggle_question',item:target.one,status:'open'}]};}
    if(/\b(ekle|kaydet|yaz)\b/.test(n)){const sub=detectSubject(text)||{subject:'Matematik',title:''};const topic=sub.title!==sub.subject?sub.title:'';const refParts=[];for(const re of [/(?:test)\s*\d+/ig,/(?:sayfa|sf)\s*\d+/ig,/(?:soru)\s*\d+/ig]){const m=String(text).match(re);if(m)refParts.push(...m);}const reference=refParts.join(' / ');let source='';const sm=String(text).match(/(?:kaynak(?:\s+adı)?\s*[:=-]?\s*)([A-Za-z0-9ĞÜŞİÖÇğüşiöç_-]+)/i);if(sm)source=sm[1];if(!source){const before=String(text).split(/test\s*\d+|sayfa\s*\d+|sf\s*\d+|soru\s*\d+/i)[0].replace(/\b(bugun|dun|yarin|matematik|fizik|kimya|biyoloji|turkce|türkçe|geometri|sorulara|soru|ekle|kaydet)\b/gi,' ').replace(/\s+/g,' ').trim();source=before.split(' ').slice(-2).join(' ');}if(!source||!reference)return {pending:{type:'question_fields',subject:sub.subject,topic,source:source||'',reference:reference||''},message:'Soruyu ekleyebilirim. Kaynak ile sayfa/test/soru bilgisini biraz daha net yazar mısın? Örn. “Orijinal, Test 7 / Soru 4”.'};return {actions:[{type:'add_question',subject:sub.subject,topic,source,reference,note:''}]};}
    return null;
  }

  function examRows(text,type){const subjects=type==='TYT'?['Türkçe','Sosyal','Matematik','Fen']:type==='AYT'?['Matematik','Fizik','Kimya','Biyoloji']:SUBJECTS.filter(x=>!['Deneme','Diğer'].includes(x));const n=fold(text),rows=[];for(const s of subjects){const key=fold(s);const idx=n.indexOf(key);if(idx<0)continue;const next=subjects.map(other=>n.indexOf(fold(other),idx+key.length)).filter(pos=>pos>=0);const seg=n.slice(idx,next.length?Math.min(...next):undefined);const d=seg.match(/(-?\d+)\s*(?:d\b|dogru\b)/),y=seg.match(/(-?\d+)\s*(?:y\b|yanlis\b)/),b=seg.match(/(-?\d+)\s*(?:b\b|bos\b)/);if(d||y||b)rows.push({subject:s,correct:Number(d?.[1]||0),wrong:Number(y?.[1]||0),blank:Number(b?.[1]||0)});}return rows;}
  function parseExamCommand(state,text){const n=fold(text);if(!/\bdeneme\b/.test(n))return null;if(parseIntervals(text).intervals.length&&!/(dogru|doğru|yanlis|yanlış|net|sonuc|sonuç|karne|kaydet|gir)\b/.test(n))return null;const target=findByTitle(state.exams||[],targetText(text));if(/\b(sil|kaldir|kaldır)\b/.test(n)){if(!target.one)return {message:ambiguity('Denemeyi',target.list)};return {actions:[{type:'delete_exam',item:target.one}]};}if(/\b(ekle|kaydet|olustur|oluştur|gir)\b/.test(n)){const type=/\bayt\b/.test(n)?'AYT':/\btyt\b/.test(n)?'TYT':'Branş';const date=parseDate(text,todayISO());const rows=examRows(text,type);let name='';const nm=String(text).match(/([A-Za-z0-9ĞÜŞİÖÇğüşiöç._-]+(?:\s+[A-Za-z0-9ĞÜŞİÖÇğüşiöç._-]+){0,2})\s+(?:TYT|AYT)?\s*deneme/i);name=nm?.[1]?.trim()||`${type} Denemesi`;const dur=parseDuration(text);if(!rows.length)return {pending:{type:'exam_rows',examType:type,date,name,duration:dur},message:`${name} için ders sonuçlarını da yazar mısın? Örn. “Türkçe 35D 5Y, Sosyal 18D 2Y, Matematik 32D 6Y 2B, Fen 18D 2Y”.`};return {actions:[{type:'add_exam',examType:type,date,name,duration:dur,ranking:'',rows}]};}return null;}

  function parseQuery(state,text){const n=fold(text),date=parseDate(text,todayISO());if(/\b(programim|programım|bugunku program|yarinki program|bloklarim|bloklarım)\b/.test(n)&&/\b(ne|neler|goster|göster|say|listele)\b/.test(n)){const bs=(state.blocks||[]).filter(b=>b.date===date).sort((a,b)=>a.start.localeCompare(b.start));return {reply:bs.length?`${fmtDate(date)}: ${bs.map(b=>`${b.start}–${b.end} ${b.title}`).join(' · ')}`:`${fmtDate(date)} için blok yok.`};}if(/\b(borclarim|borçlarım|borclar|borçlar)\b/.test(n)&&/\b(ne|neler|goster|göster|listele|kac|kaç)\b/.test(n)){const ds=state.debts||[];return {reply:ds.length?`${ds.length} borcun var: ${ds.slice(0,8).map(d=>`${d.title} (${d.value} ${d.unit})`).join(' · ')}`:'Şu an haftalık borcun yok ✨'};}if(/\b(gorevlerim|görevlerim)\b/.test(n)&&/\b(ne|neler|goster|göster|listele|kac|kaç)\b/.test(n)){const ts=(state.tasks||[]).filter(t=>!t.completed);return {reply:ts.length?`${ts.length} aktif görevin var: ${ts.slice(0,8).map(t=>t.title).join(' · ')}`:'Aktif görev havuzun boş.'};}return null;}

  function splitCommands(text){const s=String(text).replace(/\n+/g,';').replace(/\s+(?:ve\s+)?sonra\s+/gi,';');if(/\bdeneme\b/i.test(s)&&/[dD]\b|doğru|dogru/i.test(s))return [s.trim()];return s.split(/[;]+|,(?=\s*(?:bugun|bugünkü|yarin|dun|saat|\d{1,2}(?:[:.]\d{1,2})?\s*(?:-|ile)))/i).map(x=>x.trim()).filter(Boolean);}
  function parseRequest(state,text){const q=parseQuery(state,text);if(q)return q;const wholeExam=parseExamCommand(state,text);if(wholeExam&&(wholeExam.actions||wholeExam.pending||wholeExam.message))return wholeExam;const parts=splitCommands(text),actions=[];let inherited=parseDate(text,todayISO());for(const part of parts){inherited=parseDate(part,inherited);const parser=parseTaskCommand(state,part)||parseDebtCommand(state,part)||parseQuestionCommand(state,part)||parseBlockCommand(state,part,inherited);if(!parser)return {message:'Bunu tam anlayamadım. Ne üzerinde işlem yapacağımı ve istediğin değişikliği biraz daha açık söyler misin?'};if(parser.reply)return parser;if(parser.pending)return {pending:{...parser.pending,existingActions:actions.slice()},message:parser.message};if(parser.message&&!parser.actions?.length)return {message:parser.message};if(parser.actions)actions.push(...parser.actions);}return actions.length?{actions}:{message:'Bunu tam anlayamadım.'};}

  Object.assign(M,{parseRequest,examRows});
})();
