(() => {
  'use strict';
  const M=window.HakunaMataV2;
  if(!M) throw new Error('Mata core yüklenmedi');
  const {SUBJECTS,EMOJI,uid,esc,fold,todayISO,fmtDate,minute,time,duration,parseDuration,parseMetric,currentState,addMessage,friendly,actionLabel,conflict,writeState,parseRequest,examRows,openDB}=M;
  let mataActive=false, proposal=null, pending=null, injecting=false;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function messagesHTML(state){return state.assistantMessages.map(m=>`<div class="mata-message ${m.role==='user'?'user':'mata'}">${m.role==='mata'?'<img src="./assets/mata.webp" alt="" class="mata-avatar">':''}<div><div class="mata-bubble">${esc(m.text)}</div><div class="mata-time">${new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit'}).format(new Date(m.time))}</div></div></div>`).join('');}
  function proposalHTML(state){if(!proposal?.length)return '';return `<section class="mata-proposal"><div class="mata-proposal-head"><div><strong>✨ Mata’nın önizlemesi</strong><span>${proposal.length} işlem</span></div></div><div class="mata-proposal-list">${proposal.map(a=>`<div class="mata-proposal-row ${conflict(state,a)?'warning':''}"><span>${conflict(state,a)?'⚠️':'✓'}</span><div>${esc(actionLabel(a))}</div></div>`).join('')}</div><div class="mata-proposal-actions"><button class="secondary-btn" data-mata-cancel>Vazgeç</button><button class="primary-btn" data-mata-apply>${proposal.length>1?'Hepsini Uygula':'Uygula'}</button></div></section>`;}

  async function renderMata(){if(!mataActive)return;const state=await currentState(),view=$('#view'),actions=$('#topbarActions');if(!view||!actions)return;$('#pageEyebrow').textContent='Hakuna’yı konuşarak yönet';$('#pageTitle').textContent='Mata';actions.innerHTML='<span class="mata-online">● Cihaz içinde</span>';view.innerHTML=`<div class="mata-layout"><section class="card mata-chat-card"><div class="mata-chat-head"><div><div class="card-title">✨ Mata — Hakuna Asistan</div><div class="card-subtitle">Program, görev, borç, deneme ve sorularını normal konuşma diliyle yönet.</div></div><div class="mata-mini"><img src="./assets/mata.webp" alt="Mata"></div></div><div class="mata-messages" id="mataMessages">${messagesHTML(state)}${proposalHTML(state)}</div><div class="mata-input-wrap"><textarea id="mataInput" rows="2" maxlength="1200" placeholder="Mata’ya ne yapmak istediğini yaz…"></textarea><button class="mata-send" data-mata-send aria-label="Gönder">➤</button></div><div class="mata-input-hint">Örn. “11.45’teki türevin başlangıcını 11.35 yap”, “Bugünkü fiziği tamamlandı yap”, “Görev havuzuna 5 test türev ekle”.</div></section><aside class="mata-side"><section class="card mata-intro"><div class="mata-character"><img src="./assets/mata.webp" alt="Mata maskotu"></div><div class="mata-intro-copy"><div class="mata-name">Mata 💙</div><p><strong>Mata ne yapar?</strong> Hakuna’da senin elle yapabildiğin temel veri işlemlerini konuşarak yapar: blok ekler, siler, saatini/süresini/tarihini/adını değiştirir, durumunu işaretler; görev ve borç yönetir; deneme ve soru kaydeder.</p><p><strong>Nasıl kullanılır?</strong> Komut ezberleme. “Şunu 10 dakika erkene al”, “bu bloğun başlangıcını 11.35 yap”, “dünkü denemeyi kaydet” gibi doğal yaz. Değişiklikleri önce gösterir, sen onaylayınca uygular.</p></div></section><section class="card mata-examples"><div class="card-title">Deneyebileceğin şeyler</div><div class="card-subtitle">Dokunup düzenleyebilirsin.</div><div class="mata-example-list"><button data-mata-example="11.45'teki türevin başlangıç saatini 11.35 yap">11.45’teki türevin başlangıcını 11.35 yap</button><button data-mata-example="Bugünkü fiziği tamamlandı yap">Bugünkü fiziği tamamlandı yap</button><button data-mata-example="Görev havuzuna 5 test Apotemi Türev ekle">Görev havuzuna 5 test türev ekle</button><button data-mata-example="Orijinal matematik Test 7 Soru 4'ü sorulara ekle">Sorulara kaynak + soru ekle</button><button data-mata-example="Yarın 9-10 paragraf, 10-11 problem, 11.30-12.30 türev koy">Yarının birkaç bloğunu tek mesajda yaz</button></div></section></aside></div>`;
    requestAnimationFrame(()=>{const box=$('#mataMessages');if(box)box.scrollTop=box.scrollHeight;});const input=$('#mataInput');$('[data-mata-send]')?.addEventListener('click',()=>{const v=input.value;input.value='';handleSend(v)});input?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();const v=input.value;input.value='';handleSend(v);}});$$('[data-mata-example]').forEach(b=>b.onclick=()=>{input.value=b.dataset.mataExample;input.focus();});$('[data-mata-apply]')?.addEventListener('click',applyProposal);$('[data-mata-cancel]')?.addEventListener('click',async()=>{proposal=null;pending=null;const s=await currentState();addMessage(s,'mata','Tamam 💙 Bu işlemleri uygulamadım.');await writeState(s);renderMata();});markActiveNav();}

  async function handlePending(state,raw){if(!pending)return false;const base=pending.existingActions||[];
    if(pending.type==='duration'){const d=parseDuration(raw);if(!d){addMessage(state,'mata','Süreyi “50 dakika” veya “1 saat” gibi yazabilir misin?');return true;}proposal=[...base,{type:'add_block',date:pending.date,start:pending.start,end:time(minute(pending.start)+d),subject:pending.subject,title:pending.title,metricValue:pending.metric?.value||null,metricUnit:pending.metric?.unit||'test',note:''}];pending=null;addMessage(state,'mata',`${friendly('proposal')} Önizlemeyi hazırladım.`);return true;}
    if(pending.type==='partial_remaining'){const r=parseMetric(raw);if(!r){addMessage(state,'mata','Kalanı “3 test” veya “20 dakika” gibi yazabilir misin?');return true;}proposal=[...base,{type:'status_block',oldBlock:pending.block,status:'partial',remaining:r}];pending=null;addMessage(state,'mata',`${friendly('proposal')} Kalan miktarı da ekledim.`);return true;}
    if(pending.type==='question_fields'){const refParts=[];for(const re of [/(?:test)\s*\d+/ig,/(?:sayfa|sf)\s*\d+/ig,/(?:soru)\s*\d+/ig]){const m=String(raw).match(re);if(m)refParts.push(...m);}let source=String(raw).split(/test\s*\d+|sayfa\s*\d+|sf\s*\d+|soru\s*\d+/i)[0].replace(/[,:-]+$/,'').trim();const reference=refParts.join(' / ')||pending.reference;if(!source||!reference){addMessage(state,'mata','Kaynak ve soru bilgisini birlikte yazar mısın? Örn. “Orijinal, Test 7 / Soru 4”.');return true;}proposal=[...base,{type:'add_question',subject:pending.subject,topic:pending.topic,source,reference,note:''}];pending=null;addMessage(state,'mata',`${friendly('proposal')} Soruyu hazırladım.`);return true;}
    if(pending.type==='exam_rows'){const rows=examRows(raw,pending.examType);if(!rows.length){addMessage(state,'mata','Ders sonuçlarını “Türkçe 35D 5Y, Matematik 32D 6Y 2B” gibi yazar mısın?');return true;}proposal=[...base,{type:'add_exam',examType:pending.examType,date:pending.date,name:pending.name,duration:pending.duration,ranking:'',rows}];pending=null;addMessage(state,'mata',`${friendly('proposal')} Deneme kaydını hazırladım.`);return true;}
    return false;
  }

  async function handleSend(text){const raw=String(text||'').trim();if(!raw)return;const state=await currentState();addMessage(state,'user',raw);proposal=null;if(await handlePending(state,raw)){await writeState(state);return renderMata();}const r=parseRequest(state,raw);if(r.reply){addMessage(state,'mata',r.reply);await writeState(state);return renderMata();}if(r.pending){pending=r.pending;addMessage(state,'mata',`${friendly('clarify')} ${r.message}`);await writeState(state);return renderMata();}if(!r.actions?.length){addMessage(state,'mata',r.message||'Bunu tam anlayamadım.');await writeState(state);return renderMata();}proposal=r.actions;const hasConflict=proposal.some(a=>conflict(state,a));addMessage(state,'mata',`${friendly('proposal')} ${proposal.length===1?'1 işlemi':proposal.length+' işlemi'} hazırladım${hasConflict?' — saat çakışması görüyorum, önizlemeyi kontrol et':''}.`);await writeState(state);renderMata();}

  function applyBlockStatus(state,a){const b=state.blocks.find(x=>x.id===a.oldBlock.id);if(!b)return;b.status=a.status;if(a.status==='complete'){state.debts=state.debts.filter(d=>d.sourceBlockId!==b.id&&d.id!==b.sourceDebtId);}else if(a.status==='incomplete'){if(!b.sourceDebtId){const ex=state.debts.find(d=>d.sourceBlockId===b.id),value=b.metricValue||duration(b.start,b.end),unit=b.metricValue?b.metricUnit:'dakika';if(ex){ex.value=value;ex.unit=unit;}else state.debts.push({id:uid('debt'),title:b.title,subject:b.subject,value,unit,sourceBlockId:b.id,sourceDate:b.date,createdAt:new Date().toISOString()});}}else if(a.status==='partial'){const r=a.remaining;if(b.sourceDebtId){const d=state.debts.find(x=>x.id===b.sourceDebtId);if(d){d.value=r.value;d.unit=r.unit;d.title=b.title;d.subject=b.subject;}}else{const ex=state.debts.find(d=>d.sourceBlockId===b.id);if(ex){ex.value=r.value;ex.unit=r.unit;}else state.debts.push({id:uid('debt'),title:b.title,subject:b.subject,value:r.value,unit:r.unit,sourceBlockId:b.id,sourceDate:b.date,createdAt:new Date().toISOString()});}}}
  async function applyProposal(){if(!proposal?.length)return;const state=await currentState(),copy=proposal.slice();for(const a of copy){
    if(a.type==='add_block')state.blocks.push({id:uid('block'),date:a.date,start:a.start,end:a.end,title:a.title,subject:SUBJECTS.includes(a.subject)?a.subject:'Diğer',metricValue:a.metricValue||null,metricUnit:a.metricUnit||'test',note:a.note||'Mata tarafından eklendi',status:'pending',sourceDebtId:null,createdAt:new Date().toISOString()});
    else if(a.type==='delete_block')state.blocks=state.blocks.filter(b=>b.id!==a.oldBlock.id);
    else if(a.type==='edit_block')state.blocks=state.blocks.map(b=>b.id===a.oldBlock.id?{...b,...a.patch}:b);
    else if(a.type==='status_block')applyBlockStatus(state,a);
    else if(a.type==='add_task')state.tasks.push({id:uid('task'),title:a.title,subject:a.subject,value:a.value||null,unit:a.unit||'test',note:a.note||'',completed:false,createdAt:new Date().toISOString()});
    else if(a.type==='delete_task')state.tasks=state.tasks.filter(x=>x.id!==a.item.id);
    else if(a.type==='toggle_task'){const t=state.tasks.find(x=>x.id===a.item.id);if(t)t.completed=a.completed;}
    else if(a.type==='schedule_task')state.blocks.push({id:uid('block'),date:a.date,subject:a.item.subject,title:a.item.title,start:a.start,end:a.end,metricValue:a.item.value||null,metricUnit:a.item.unit||'test',note:a.item.note||'Görev havuzundan',status:'pending',sourceDebtId:null,createdAt:new Date().toISOString()});
    else if(a.type==='add_debt')state.debts.push({id:uid('debt'),title:a.title,subject:a.subject,value:a.value,unit:a.unit,sourceBlockId:null,sourceDate:a.sourceDate||todayISO(),createdAt:new Date().toISOString()});
    else if(a.type==='delete_debt')state.debts=state.debts.filter(x=>x.id!==a.item.id);
    else if(a.type==='schedule_debt')state.blocks.push({id:uid('block'),date:a.date,subject:a.item.subject,title:a.item.title,start:a.start,end:a.end,metricValue:a.item.value,metricUnit:a.item.unit,note:'Haftalık borç',status:'pending',sourceDebtId:a.item.id,createdAt:new Date().toISOString()});
    else if(a.type==='add_question')state.questions.push({id:uid('q'),subject:a.subject,topic:a.topic||'',source:a.source,reference:a.reference,note:a.note||'',status:'open',createdAt:new Date().toISOString()});
    else if(a.type==='delete_question')state.questions=state.questions.filter(x=>x.id!==a.item.id);
    else if(a.type==='toggle_question'){const q=state.questions.find(x=>x.id===a.item.id);if(q)q.status=a.status;}
    else if(a.type==='add_exam')state.exams.push({id:uid('exam'),type:a.examType,date:a.date,name:a.name,duration:a.duration||null,ranking:a.ranking||'',rows:a.rows,createdAt:new Date().toISOString()});
    else if(a.type==='delete_exam')state.exams=state.exams.filter(x=>x.id!==a.item.id);
  }proposal=null;addMessage(state,'mata',`${friendly('applied')} ${copy.length===1?'İşlemi uyguladım.':copy.length+' işlemi tek seferde uyguladım.'}`);await writeState(state);renderMata();}

  function markActiveNav(){$$('[data-mata-nav]').forEach(b=>b.classList.add('active'));$$('[data-nav]').forEach(b=>b.classList.remove('active'));}
  function addNav(){if(injecting)return;injecting=true;const side=$('#sidebarNav');if(side&&!side.querySelector('[data-mata-nav]')){const b=document.createElement('button');b.className='nav-button';b.dataset.mataNav='1';b.innerHTML='<span class="nav-icon">✨</span><span class="nav-label">Mata</span>';b.onclick=()=>{mataActive=true;renderMata()};const settings=side.querySelector('[data-nav="settings"]');side.insertBefore(b,settings||null);}const bottom=$('#bottomNav');if(bottom&&!bottom.querySelector('[data-mata-nav]')){const b=document.createElement('button');b.dataset.mataNav='1';b.innerHTML='<span class="nav-icon">✨</span><span>Mata</span>';b.onclick=()=>{mataActive=true;renderMata()};const more=bottom.querySelector('[data-nav="more"]');bottom.insertBefore(b,more||null);bottom.classList.add('mata-bottom-nav');}if(mataActive)markActiveNav();injecting=false;}
  function interceptAppNav(){document.addEventListener('click',e=>{const b=e.target.closest?.('[data-nav]');if(!b||!mataActive)return;const target=b.dataset.nav;if(target==='more'){mataActive=false;return;}e.preventDefault();e.stopImmediatePropagation();sessionStorage.setItem('hakuna_mata_target',target);location.reload();},true);}
  function resumeTarget(){const target=sessionStorage.getItem('hakuna_mata_target');if(!target)return;sessionStorage.removeItem('hakuna_mata_target');setTimeout(()=>document.querySelector(`[data-nav="${target}"]`)?.click(),220);}
  function observe(){const ob=new MutationObserver(()=>{addNav();});ob.observe(document.body,{childList:true,subtree:true});}
  async function init(){try{await openDB();}catch(e){console.warn('Mata DB',e);return;}addNav();interceptAppNav();observe();resumeTarget();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
