const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function setup(){let owner='a';const box={window:{},localStorage:{getItem:()=>owner},console,document:{documentElement:{dataset:{}},createElement:()=>({}),head:{appendChild(){}}}};vm.createContext(box);for(const f of ['mata-core-v2.js','mata-nlu-v2.js','mata-insights-v1.js','mata-brain-v3.js','mata-capabilities-v4.js','mata-actions-v4.js','mata-conversation-v4.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),box);const M=box.window.HakunaMataV2;let state={blocks:[],planItems:[],tasks:[],debts:[],questions:[],exams:[],assistantMessages:[],settings:{},selectedDate:M.todayISO()};state=M.actionsV4.reduce(state,[{type:'record',collection:'questions',op:'add',data:{subject:'Matematik',source:'Kitap A',reference:'Soru 1'}},{type:'record',collection:'questions',op:'add',data:{subject:'Matematik',source:'Kitap B',reference:'Soru 2'}}]);return {M,state,switchOwner:()=>owner='b',parse:t=>M.parseRequest(state,t)};}
test('list → second question solved resolves stable ID',()=>{const {parse,state}=setup();parse('matematik sorularımı listele');const r=parse('ikincisini çözdüm');assert.equal(r.actions?.[0].before.id,state.questions[1].id);assert.equal(r.actions[0].status,'solved');});
test('list references reject changed records',()=>{const {parse,state}=setup();parse('sorularımı listele');state.questions[1].note='external';assert.match(parse('ikincisini sil').reply,/değişmiş/);});
test('plural refers to the filtered list, not entire collection',()=>{const {parse,state}=setup();state.questions[1].subject='Fizik';parse('matematik sorularımı listele');assert.equal(parse('bunları sil').actions.length,1);});
test('ambiguous delete asks to choose then uses snapshot',()=>{const {parse,state}=setup();assert.match(parse('matematik sorusunu sil').reply,/Hangisi/);const r=parse('2');assert.equal(r.actions[0].before.id,state.questions[1].id);});
test('guided plan card creation gathers missing fields',()=>{const {parse,M,state}=setup();assert.match(parse('plan kartı ekle').reply,/başlık/);assert.match(parse('Türev tekrarı').reply,/ders/);const r=parse('Matematik');assert.equal(r.actions[0].collection,'planItems');assert.equal(M.actionsV4.reduce(state,r.actions).planItems[0].title,'Türev tekrarı');});
test('edit supports named note, topic and reference fields',()=>{const {parse}=setup();parse('sorularımı listele');assert.match(parse('ikincisini düzenle').reply,/Neyi/);const r=parse('not: Hocaya sor; konu: İntegral; referans: Sayfa 12');assert.equal(r.actions[0].data.note,'Hocaya sor');assert.equal(r.actions[0].data.topic,'İntegral');});
test('cancel abandons pending create without actions',()=>{const {parse}=setup();parse('plan kartı ekle');assert.equal(parse('iptal').cancel,true);assert.equal(parse('Matematik').actions,undefined);});
test('owner change abandons pending operation',()=>{const {parse,switchOwner}=setup();parse('plan kartı ekle');switchOwner();assert.match(parse('Türev').reply,/Hesap değişti/);});
test('move listed cards to tomorrow',()=>{const {parse,state,M}=setup();state.planItems=M.actionsV4.reduce(state,[{type:'record',collection:'planItems',op:'add',data:{title:'Test',subject:'Matematik',date:M.todayISO()}}]).planItems;parse('plan kartlarını listele');const r=parse('bunları yarına taşı');assert.equal(r.actions[0].data.date,M.addDays(M.todayISO(),1));});
test('exam guided rows honor exam type',()=>{const {parse,M,state}=setup();assert.match(parse('deneme ekle').reply,/sınav türü/);parse('TYT');parse('345 denemesi');const r=parse('Türkçe 35D 5Y, Matematik 30D 5Y 5B');assert.equal(M.actionsV4.reduce(state,r.actions).exams[0].rows[1].blank,5);});
test('implicit block commands keep legacy parsing',()=>{const {parse,M,state}=setup();const r=parse('Yarın 09:00-09:50 matematik ekle');assert.equal(M.actionsV4.reduce(state,r.actions).blocks.length,1);});
